'use client'
import type { Metadata } from 'next'

import { ReactNode } from 'react'
import { Provider } from 'react-redux'

import { store } from '../store'

import '../styles/index.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={'en'}>
      <Provider store={store}>
        <body>{children}</body>
      </Provider>
    </html>
  )
}
