export const Path = {
  main: '/',
  favorites: '/favorites',
  forgotPassword: '/forgot-password',
  messenger: '/messenger',
  privacyPolicy: '/privacy-policy',
  profile: (id: number) => `/profile?id=${id}`,
  recallEmail: '/recall-email',
  registrationConfirmation: '/registration-confirmation',
  search: '/search',
  settings: {
    main: '/settings',
    subscriptions: '/settings/subscriptions',
    devices: '/settings/devices',
    payments: '/settings/payments',
  },
  signIn: '/sign-in',
  signUp: '/sign-up',
  statistics: '/statistics',
  termsOfService: '/terms-of-service',
  passwordRecovery: '/password-recovery',
} as const
